name: Sonatype Nexus CD

on: 
  workflow_dispatch: 
    inputs: 
      actions:
        type: choice
        options:
          - apply
          - destroy
        description: Please select apply or destroy

      environment: 
        type: choice
        options:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
        description: Please select environment to deploy to

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout Private Infrastructure Repository
        uses: actions/checkout@v4
        with:
          repository: 'issallina/sonatype-nexus-project'
          token: ${{ secrets.INFRA_REPO_PAT }}
          path: sonatype-nexus-project 

      - name: Create tfvars file
        run: echo "$TFVARS_CONTENT" > sonatype-nexus-project/terraform/terraform.tfvars
        env:
          TFVARS_CONTENT: ${{ secrets.TFVARS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.environment }}

      - name: Terraform Init
        run: |
          cd sonatype-nexus-project/terraform
          terraform init

      - name: Terraform Apply or Destroy
        run: |
          cd sonatype-nexus-project/terraform
                    
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
          
          if [[ "${{ inputs.actions }}" == "apply" ]]
          then 
            terraform apply -auto-approve
          else 
            terraform destroy -auto-approve
          fi
